1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

ans. NumPy is a crucial library for scientific computing and data analysis in Python, providing efficient support for large, multi-dimensional arrays and a wide range of mathematical functions. Here's a brief overview of its purpose and advantages:

*) Purpose of NumPy:
    
     i) Efficient Array Computations: Optimized for performance with n-dimensional arrays.
     ii) Mathematical Functions: Extensive library for complex calculations.
     iii) Linear Algebra and Random Number Generation: Tools for common scientific tasks.
     iv) Interoperability: Works seamlessly with other Python libraries.
*) Advantages of NumPy:
     
     i) Performance: Up to 50 times faster than native Python lists.
     ii) Memory Efficiency: More compact than Python lists.
     iii) Vectorization: Element-wise operations without explicit loops.
     iv) Broadcasting: Simplifies operations between arrays of different shapes.
     v) Comprehensive Library: Extensive functions for various tasks.
     vi) Integration: Works well with libraries like pandas, Matplotlib, and TensorFlow.
*) Enhancing Python's Capabilities:
     
     i) Ease of Use: Intuitive and straightforward API.
     ii) Standardization: Consistent array structure across scientific libraries.
     iii) High-Level Operations: Simple syntax for complex tasks.
     iv) Support for Multi-Dimensional Data: Efficient handling of complex data structures.
     v) In summary, NumPy boosts Python's efficiency, performance, and capability for numerical operations, making it indispensable for          data scientists and researchers.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

np.mean() vs. np.average()
 
 I) np.mean():

     i) Purpose: Computes the arithmetic mean (simple average).
     ii) Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
    iii) Usage: Use when all elements are equally important, and no weights are needed.

II) np.average():

        i) Purpose: Computes the weighted average.
        ii) Syntax: np.average(a, axis=None, weights=None, returned=False)
        iii) Usage: Use when elements have different weights or importance.

*)key Differences:
  a) Weights:
        i) np.mean() does not use weights.
        ii) np.average() can use a weights parameter.
  b)Return Values:
        i)np.mean() returns a single mean value.
        ii)np.average() can return both the weighted average and the sum of weights (if returned=True).
*) When to Use:
       i) Use np.mean():
             * For simple, unweighted averages.
       ii) Use np.average():
             * For weighted averages where elements contribute differently.

In [3]:
import numpy as np

data = np.array([1, 2, 3, 4])
mean_value = np.mean(data)  # Simple average
weights = np.array([1, 2, 3, 4])
weighted_average = np.average(data, weights=weights)  # Weighted average

print("Mean:", mean_value)
print("Weighted Average:", weighted_average)


Mean: 2.5
Weighted Average: 3.0


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

ans. Reversing a NumPy array can be done using slicing or the np.flip() function.

*) Methods for Reversing a NumPy Array:

        i)Using Slicing: This is the most straightforward way to reverse an array.
        ii) Using np.flip(): This function allows you to reverse the order of elements along specified axes.

In [5]:
#1D array example

# i) using slicing
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse using slicing
reversed_1d_slicing = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array using slicing:", reversed_1d_slicing)


Original 1D array: [1 2 3 4 5]
Reversed 1D array using slicing: [5 4 3 2 1]


In [6]:
# using np.flip()
# Reverse using np.flip
reversed_1d_flip = np.flip(arr_1d)

print("Reversed 1D array using np.flip:", reversed_1d_flip)


Reversed 1D array using np.flip: [5 4 3 2 1]


In [7]:
# 2D Array
# reveraing rows
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

reversed_rows = arr2d[::-1, :]
print(reversed_rows)  


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [8]:
# reversing columns
reversed_cols = arr2d[:, ::-1]
print(reversed_cols) 

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [12]:
#using n.flip()

# Reversing rows of 2D array
reversed_rows = np.flip(arr2d, axis=0)
print(reversed_rows)

# Reversing columns of 2D array
reversed_cols = np.flip(arr2d, axis=1)
print(reversed_cols)


[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

ans. To determine the data type of elements in a NumPy array, you can use the dtype attribute:

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  

int64


*) Importance of Data Types in Memory Management and Performance:
Data types play a crucial role in memory management and performance optimization in NumPy:

   i) Memory Efficiency:

        a)Smaller Data Types: Using smaller data types (e.g., int16, float32) can significantly reduce memory consumption, especially for large arrays.
        b)Memory Allocation: NumPy allocates contiguous memory blocks for arrays. The data type determines the size of each element, which directly impacts the overall memory footprint.

   ii) Computational Efficiency:

      a)Optimized Operations: NumPy's operations are often optimized for specific data types. Using appropriate data types can lead to faster computations.
       b)Cache Efficiency: Smaller data types can fit more elements into cache, improving performance by reducing memory access times.

   iii)Precision:

      a) Data Loss: Choosing a data type with insufficient precision can lead to data loss or inaccurate results.
      b) Balance: It's essential to balance precision and memory usage. For example, if high precision is not required,
          using float32 instead of float64 can save memory.


    iv) Considerations for Data Type Selection:

        a) Range of Values: The data type should be able to represent the full range of values in the array.
        b) Precision Requirements: The data type should provide sufficient precision for the calculations.
        c) Memory Constraints: If memory is limited, consider using smaller data types.
        d) Performance Considerations: The data type can impact computational performance, especially for large arrays.

*)By carefully considering these factors, you can optimize your NumPy arrays for both memory usage and computational efficiency.


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ans. Defining ndarray in NumPy:
     In NumPy, an ndarray (n-dimensional array) is a powerful multi-dimensional array object that forms the core of the library. 
     It is designed to handle large data sets efficiently and supports a variety of mathematical operations.


A) Key Features of ndarray

i) N-Dimensional:

    Supports arrays of any dimension (1D, 2D, 3D, etc.), making it versatile for various types of data structures like vectors, matrices, and tensors.

ii) Homogeneous Data Types:

    All elements in an ndarray are of the same type, ensuring efficient memory use and performance. The data type (dtype) can be specified at the time of array creation.

iii) Efficient Memory Storage:

    Elements are stored in contiguous memory blocks, which enhances performance for operations and allows for efficient use of the CPU cache.


iv) Vectorized Operations:

    supports element-wise operations and broadcasting, which means operations can be applied simultaneously across all elements of the array without explicit loops.

v) Mathematical Functions:

      NumPy provides a rich library of functions to perform complex mathematical operations directly on ndarray objects.


vi) Shape and Reshape:

      The shape of an ndarray can be altered without copying the data, allowing for flexible manipulation of data structures.

vii) Indexing and Slicing:

        Supports advanced indexing and slicing, enabling easy access and manipulation of subsets of the array.


B) How ndarray Differs from Standard Python Lists

I)Homogeneity:

    i) ndarray: Elements must be of the same data type.
    ii) Python Lists: Can contain elements of different data types.

II) Memory Efficiency:

     i) ndarray: Stores elements in contiguous memory, reducing overhead and improving access speed.
     ii) Python Lists: Elements are stored as separate objects, leading to higher memory overhead and slower access.

III)Performance:

      i) ndarray: Optimized for numerical operations, supporting vectorized operations that are much faster than loops
          in standard Python.
      ii) Python Lists: Not optimized for numerical operations, requiring explicit loops for element-wise operations, which are slower.

IV) Built-in Functions:

     i) ndarray: Comes with a wide range of built-in functions for mathematical, statistical, and linear algebra operations.
     ii) Python Lists: Limited built-in functionality; external libraries or manual implementations are often required
     for advanced operations.

V) Broadcasting:

    i)ndarray: Supports broadcasting, allowing operations on arrays of different shapes.
    ii) Python Lists: No native support for broadcasting; manual handling is needed.

VI)Shape Manipulation:

    i)ndarray: Easy to reshape, flatten, and manipulate the structure of the array without data copying.
    ii)Python Lists: Reshaping or changing the structure often requires nested loops and is not straightforward.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

ans. NumPy Arrays vs. Python Lists: 
NumPy arrays offer significant performance advantages over Python lists, especially for large-scale numerical operations. Here's a breakdown of the key reasons:

1. Memory Efficiency:

       i) Homogeneous Data Type: NumPy arrays store elements of the same data type contiguously in memory, reducing memory overhead.
       ii) Fixed-Size Allocation: NumPy allocates memory for the entire array upfront, avoiding dynamic memory allocation
           and deallocation, which can be expensive.

3. Vectorization:

        i)Element-wise Operations: NumPy allows you to perform operations on entire arrays at once, without explicit looping.
          This is significantly faster than using Python loops.
        ii) Optimized C Implementation: NumPy's core operations are implemented in C, providing a significant speedup.

3. Broadcasting:

       Flexible Operations: NumPy's broadcasting rules enable operations on arrays of different shapes, simplifying complex calculations.

4. Specialized Functions:

        Optimized Libraries: NumPy leverages highly optimized libraries like BLAS and LAPACK for linear algebra operations.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

ans. Vstack and hstack in Numpy:

*)NumPy's vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively.

A) vStack(): Vertical Stacking

i) Purpose: Stacks arrays vertically, row-wise.
ii) Syntax: np.vstack((array1, array2, ...))

B)hStack(): Horizontal Stacking

i) Purpose: Stacks arrays horizontally, column-wise.
ii) Syntax: np.hstack((array1, array2, ...))

In [14]:
# example of Vstack
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

stacked_array = np.vstack((array1, array2))
print(stacked_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# example of Hstack
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

stacked_array = np.hstack((array1, array2))
print(stacked_array)

[[1 2 5 6]
 [3 4 7 8]]


a) Summary of vstack() and hstack()
i) np.vstack():
* Stacks arrays vertically.
* The result has more rows and the same number of columns.
ii) np.hstack():
* Stacks arrays horizontally.
* The result has more columns and the same number of rows.

b) Use Cases:
* Use vstack() when you want to combine datasets with the same number of features (columns) into a larger dataset.
* Use hstack() when you want to combine datasets with the same number of samples (rows) by adding more features (columns).

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

ans. In NumPy, the methods fliplr() and flipud() are used to flip arrays along different axes. They serve to reverse the order of elements in an array but do so in distinct ways based on the array's dimensions.

*) Differences between fliplr() and flipud()

I) fliplr() (Flip Left to Right):

     * Purpose: Flips an array horizontally (left to right).
     * Effect: The columns of the array are reversed, while the rows remain in their original order.
     * Applicable Dimensions: This method can only be applied to 2D arrays (matrices). If used on a 1D array, 
         it will return the same array as there are no columns to flip. 
        

II) flipud() (Flip Up to Down):

     * Purpose: Flips an array vertically (up to down).
     * Effect: The rows of the array are reversed, while the columns remain in their original order.
     * Applicable Dimensions: This method can also be applied to 2D arrays. Like fliplr(), if applied to a 1D array,
        it willreturn the same array.

In [16]:
# example of fliplr()
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Flip left to right
flipped_lr = np.fliplr(array_2d)

print("Original Array:\n", array_2d)
print("Flipped Left to Right:\n", flipped_lr)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped Left to Right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [17]:
# example of flipud()
# Flip up to down
flipped_ud = np.flipud(array_2d)

print("Flipped Up to Down:\n", flipped_ud)


Flipped Up to Down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


* Effects on Various Array Dimensions

i) 1D Arrays:
* fliplr(): Returns the same 1D array as there are no columns to flip.
* flipud(): Also returns the same 1D array, as there are no rows to flip.

ii) 3D Arrays:

*For 3D arrays, fliplr() and flipud() only operate along the last two dimensions. Specifically, fliplr() flips the last dimension (usually columns), and flipud() flips the second last dimension (usually rows) across the first axis (depth).

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

ans. array_split() in NumPy: 

 NumPy's array_split() function is used to split an array into multiple sub-arrays. It's particularly useful for dividing large arrays into smaller chunks for parallel processing or for specific data analysis tasks.

* Key Features:

        i) Uneven Splits: It can handle uneven splits, ensuring that each sub-array has approximately the same number of elements,
          but the last sub-array might have fewer elements.
        ii) Flexible Splitting: You can specify the number of splits or the size of each split.
        iii) Preserves Array Structure: The resulting sub-arrays maintain the original array's data type and shape,
              except for the first dimension, which is split.

In [19]:
# example
import numpy as np

arr = np.arange(10)

# Split into 3 sub-arrays
split_arr = np.array_split(arr, 3)
print(split_arr)

# Split into sub-arrays of size 2, with the last sub-array having the remaining elements
split_arr = np.array_split(arr, 2)
print(split_arr)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


* Handling Uneven Splits:

When the array cannot be evenly divided into the specified number of sub-arrays, array_split() ensures that the last sub-array might have fewer elements. This behavior is particularly useful when dealing with arrays of varying sizes or when you need to distribute data across multiple processes.By understanding the array_split() function and its handling of uneven splits, you can effectively divide and conquer your data analysis tasks, making them more efficient and manageable.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

ans.A) Vectorization:
 * Definition: Vectorization converts operations that would normally use loops into single operations that apply to entire arrays.
 * Benefits:

       i) Performance: Significantly faster than loops due to optimized low-level implementations.
       ii) Conciseness: Leads to more readable and maintainable code.

B)Broadcasting:
 * Definition: Broadcasting allows NumPy to perform operations on arrays of different shapes by expanding the smaller array to match the larger one.
 * Benefits:
   
        i) Efficiency: Reduces the need for manual shape adjustments, enabling direct operations on arrays of different sizes.
        ii) Flexibility: Simplifies operations involving scalars and arrays or arrays of different dimensions.


In [21]:
# example of vectorization
import numpy as np

# Vectorized operation
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)  # Output: [5 7 9]

[5 7 9]


In [22]:
# example of broadcasting
import numpy as np

arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])

arr2 = np.array([10, 20, 30])

result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]


* Contribution to Efficient Array Operations:

i) Reduced Computation Time: Both vectorization and broadcasting leverage low-level optimizations, which reduce computation times significantly compared to traditional iterative approaches.

ii) Simplified Code: These concepts allow for more concise, readable, and maintainable code by avoiding explicit loops, which can be prone to errors and less efficient.

iii) Memory Efficiency: Broadcasting eliminates the need to create large temporary arrays, as the operations are performed in a way that efficiently utilizes memory.

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(arr)

# Interchange rows and columns (transpose)
transposed_arr = arr.T

print("\nTransposed array:")
print(transposed_arr)

Original array:
[[ 51 100   4]
 [ 90  63  20]
 [ 20  30  77]]

Transposed array:
[[ 51  90  20]
 [100  63  30]
 [  4  20  77]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [3]:
import numpy as np

# Generate a 1D array with 10 elements
arr = np.arange(10)

# Reshape it into a 2x5 array
arr_2x5 = arr.reshape(2, 5)

print("2x5 array:")
print(arr_2x5)

# Reshape it into a 5x2 array
arr_5x2 = arr.reshape(5, 2)

print("\n5x2 array:")
print(arr_5x2)

2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [5]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to create a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:\n", array_4x4)
print("6x6 Array with Border of Zeros:\n", array_6x6)


Original 4x4 Array:
 [[0.25558344 0.35181777 0.50417518 0.99433914]
 [0.19335841 0.58682783 0.04657539 0.40337027]
 [0.88573267 0.38839841 0.9204615  0.15579227]
 [0.80362399 0.6818603  0.35213736 0.68204452]]
6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.25558344 0.35181777 0.50417518 0.99433914 0.        ]
 [0.         0.19335841 0.58682783 0.04657539 0.40337027 0.        ]
 [0.         0.88573267 0.38839841 0.9204615  0.15579227 0.        ]
 [0.         0.80362399 0.6818603  0.35213736 0.68204452 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [6]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)

print(array)


[10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [8]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

# Print the results
print("Original Array:", array)
print("Uppercase Array:", uppercase_array)
print("Lowercase Array:", lowercase_array)
print("Title Case Array:", titlecase_array)
print("Capitalize Array:", capitalize_array)


Original Array: ['python' 'numpy' 'pandas']
Uppercase Array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase Array: ['python' 'numpy' 'pandas']
Title Case Array: ['Python' 'Numpy' 'Pandas']
Capitalize Array: ['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [9]:
import numpy as np

words = np.array(["hello", "world", "numpy"])

# Insert a space between each character
spaced_words = np.char.replace(words, '', ' ')

print(spaced_words)

[' h e l l o ' ' w o r l d ' ' n u m p y ']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [10]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition_result = np.add(array1, array2)

# Element-wise subtraction
subtraction_result = np.subtract(array1, array2)

# Element-wise multiplication
multiplication_result = np.multiply(array1, array2)

# Element-wise division
division_result = np.divide(array1, array2)

# Print the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise Addition:\n", addition_result)
print("Element-wise Subtraction:\n", subtraction_result)
print("Element-wise Multiplication:\n", multiplication_result)
print("Element-wise Division:\n", division_result)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [11]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the results
print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [13]:
import numpy as np

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers
arr = np.random.randint(0, 1001, 100)

# Find prime numbers
prime_numbers = arr[np.vectorize(is_prime)(arr)]

print("Prime numbers in the array:")
print(prime_numbers)

Prime numbers in the array:
[787 467 401 359 601  89 787 631 937 619 797 179 167 269 761 797 419 499]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages

In [19]:
import numpy as np

# Generate a NumPy array representing daily temperatures for a 30-day month
daily_temperatures = np.random.randint(10, 41, size=30)  # Temperatures between 10 and 40 degrees

# Reshape the array to fit 4 full weeks (4x7) and ignore last two days
weeks = daily_temperatures[:28].reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weeks, axis=1)

# Display the results
print("Daily Temperatures (first 28 days):\n", daily_temperatures[:28])
print("Weekly Temperatures:\n", weeks)
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures (first 28 days):
 [22 23 16 38 16 27 23 36 29 13 34 39 34 15 33 40 32 32 14 37 25 11 22 16
 40 10 30 37]
Weekly Temperatures:
 [[22 23 16 38 16 27 23]
 [36 29 13 34 39 34 15]
 [33 40 32 32 14 37 25]
 [11 22 16 40 10 30 37]]
Weekly Averages:
 [23.57142857 28.57142857 30.42857143 23.71428571]
